import Head from 'next/head'
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from 'react-icons/ai'
import { SiKaggle } from 'react-icons/si'
import clientPromise from "../lib/mongodb";
import { Analytics } from '@vercel/analytics/react';


export default function Home( {profile} ) {

  return (
    <div className="text-black bg-white min-h-screen min-w-screen p-6 md:p-10 lg:p-20">
    <Head>
      <title>janinnm</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="text-black bg-white mx-auto max-w-3xl">
      <section className="text-black bg-white py-8 px-4 md:py-16 md:px-8">
        <nav className="py-10 mb-20 flex justify-between items-center">
          <h1 className="text-xl md:text-2xl lg:text-3xl text-black font-bold">janinnm</h1>
          <ul className="flex items-center">
            <li><a className="bg-black text-white px-4 py-2 md:px-6 lg:px-8 rounded-md ml-6 flex" href="mailto:janin.nicole.manalili@gmail.com">Contact Me</a></li>
          </ul>
        </nav>  
        <div className="py-1">
          <h2 className="text-2xl md:text-3xl lg:text-4xl py-1 text-black font-medium">{profile[0]?.name}</h2>
          <h3 className="text-lg md:text-xl lg:text-2xl text-black py-1">{profile[0]?.header}</h3>
        </div>
        <div className="text-2xl md:text-3xl flex justify-left gap-4 md:gap-8 py-3 text-gray-600">
          <a href="https://www.linkedin.com/in/janinmanalili/"><AiFillLinkedin/></a> 
          <a href="https://github.com/janinnm"><AiFillGithub/></a> 
          <a href="https://www.instagram.com/janinnvm/"><AiFillInstagram/></a>  
        </div>
        <p className="text-sm md:text-base lg:text-lg text-black text-justify py-1">
          {profile[0]?.description}
        </p>
      </section>
      </main>

      <footer className="text-base text-black bg-white flex justify-center items-center fixed bottom-0 left-0 w-full h-10">
          <h2>© Copyright 2024 Janin Manalili.</h2>
      </footer>

    <Analytics />

    </div>
  )
}

export async function getServerSideProps() {
  try {
      const client = await clientPromise;
      const db = client.db("Portfolio");

      const profile = await db
        .collection("profile")
        .find({})
        .limit(1)
        .toArray();

      return {
          props: { profile: JSON.parse(JSON.stringify(profile)) },
      };
  } catch (e) {
      console.error(e);
  }
}
