import Head from 'next/head'
import Link from 'next/link'
import { BiLinkExternal } from 'react-icons/bi'

export default function Projects() {
    return (
      <div className="bg-slate-900 min-h-screen min-w-fit">
        <Head>
          <title>Janin Manalili</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className="bg-slate-900 px-10"> 
            <nav className="py-10 mb-12 flex justify-between">
                <h1 className="text-xl text-white"> janinnm </h1>
                <ul className="flex items-center">
                <Link href="/"><li className="text-white cursor-pointer text-1xl px-5"> Home </li></Link>
                <Link href="/projects"><li className="text-white cursor-pointer text-1xl px-5"> Projects </li></Link>
                <a href="/#skills"><li className="text-white cursor-pointer text-1xl px-5"> Skills </li></a>
                <li><a className="bg-cyan-500 text-white px-4 py-2 rounded-md ml-8 flex" href="mailto:jvmanalili1@up.edu.ph"> Contact Me</a></li>
                </ul>
            </nav>  
          <section id="projects" className="bg-slate-900 p-10">
            <div className="text-white text-left p-10 flex flex-wrap justify-around">
              <h3 className="text-white text-3xl py-1">Projects</h3>
              <ul className="py-5 list-outside ml-6">
                <li className="text-2xl text-teal-600 flex items-start">House School?: A Home School Organization App <a href="https://github.com/House-School/House-School"><BiLinkExternal/></a> </li>
                  <p className="text-sm text-md leading-8 text-gray-400 "> A user-friendly course organization app for teachers, homeschooling parents and students. 
                  Using the MERN Stack following the AGILE methodology. [Sep21 - Jun22]</p>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">MongoDB</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Express</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Reactjs</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Redux</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Nodejs</span>
                <li className="mt-5 text-2xl text-teal-600 border-t-[1px] border-gray-500 flex items-start">sakUNA <a href="https://github.com/CS180-2122-sakUNA/sakUNA"><BiLinkExternal/></a></li>
                  <p className="text-sm text-md leading-8 text-gray-400 "> sakUNA is an application that maps out areas experiencing disasters with the 
                  purpose of providing disaster response and recovery efficiently based on tweets gathered in Twitter. [May22 - Jun22] </p>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">folium</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">pandas</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">scikit-learn</span>
                <li className="mt-5  text-2xl text-teal-600 border-t-[1px] border-gray-500">Wordle Clone App</li>
                  <p className="text-sm text-md leading-8 text-gray-400"> Implemented an application that resembles the Wordle game in Python by employing object oriented
                  programming concepts using the Python package, BeeWare. [Jan22 - Feb22] </p>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">BeeWare</span>
                <li className="mt-5  text-2xl text-teal-600 border-t-[1px] border-gray-500">File Server</li>
                  <p className="text-sm text-md leading-8 text-gray-400"> Implemented a file server in Linux using threads in C with concurrency that performs read, write, and empty
                  commands on files by applying knowledge on operating systems. [Jan22] </p>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">C</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Linux</span>       
                <li className="mt-5  text-2xl text-teal-600 border-t-[1px] border-gray-500">Rubik&apos;s Cube Simulator</li>
                  <p className="text-sm text-md leading-8 text-gray-400"> Implemented a Rubik&apos;s Cube Simulator in MIPS Assembly Language and Python. [Aug21]</p> 
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Assembly</span>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Python</span>
                <li className="mt-5  text-2xl text-teal-600 border-t-[1px] border-gray-500">AppBeat</li>
                  <p className="text-sm text-md leading-8 text-gray-400"> A rhythm game made in Python and package, pyglet. [Nov19 - Dec19]</p>
                  <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 mb-2.5 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">pyglet</span>             
              </ul>
            </div>
          </section>
  
        </main>
  
        <footer className="text-white flex justify-center items-center fixed bottom-0 left-0 bg-slate-800 w-screen h-10">
          <h2>© Copyright 2022 Janin Manalili.</h2>
        </footer>
  
      </div>
    )
  }
  